Rails.application.routes.draw do
  resources :demo_pop_race_00_10ms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'api/carto#diversity1'
  # get '/http://127.0.0.1:3000/diversity%20muni_id,nhwhi_00p,nhwhi_10p,nhwh_pdif,nhaa_pdif,lat_pdif,nhas_pdif,municipal%20FROM%20demo_pop_race_00_10m', to: 'carto#diversity'
  namespace :api do
    get '/diversity1', to: 'carto#diversity1'
    get '/criminal_justice1', to: 'carto#criminal_justice1'
    get '/criminal_justice2', to: 'carto#criminal_justice2'
    get '/education1', to: 'carto#education1'
    get '/education2', to: 'carto#education2'
    get '/employment1', to: 'carto#employment1'
    get '/employment2', to: 'carto#employment2'
    get '/employment3', to: 'carto#employment3'
    get '/employment4', to: 'carto#employment4'
    get '/employment5', to: 'carto#employment5'
    get '/employment6', to: 'carto#employment6'
    get '/employment7', to: 'carto#employment7'
    get '/health1', to: 'carto#health1'
    get '/health2', to: 'carto#health2'
    get '/home_ownership1', to: 'carto#home_ownership1'
    get '/home_ownership2', to: 'carto#home_ownership2'
    get '/housing1', to: 'carto#housing1'
    get '/housing2', to: 'carto#housing2'
    get '/housing3', to: 'carto#housing3'
    get '/housing4', to: 'carto#housing4'
    get '/housing5', to: 'carto#housing5'
    get '/income1', to: 'carto#income1'
    get '/income2', to: 'carto#income2'
    get '/income3', to: 'carto#income3'
    get '/income4', to: 'carto#income4'
    get '/income5', to: 'carto#income5'
    get '/seniors1', to: 'carto#seniors1'
    get '/seniors2', to: 'carto#seniors2'
    get '/seniors3', to: 'carto#seniors3'
    get '/seniors4', to: 'carto#seniors4'
    get '/seniors5', to: 'carto#seniors5'
    get '/seniors6', to: 'carto#seniors6'
  end
end
